version: 2

updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    labels:
      - "dependencies"
      - "github-actions"
    groups:
      github-actions:
        patterns:
          - "*"

  - package-ecosystem: "nuget"
    directory: "/"
    schedule:
      interval: "weekly"
    labels:
      - "dependencies"
      - "dotnet"
      - "nuget"
    groups:
      nuget-dependencies:
        patterns:
          - "*"

  - package-ecosystem: "dotnet-sdk"
    directory: "/"
    schedule:
      interval: "weekly"
    labels:
      - "dependencies"
      - "dotnet"
      - "sdk"

  - package-ecosystem: "pre-commit"
    directory: "/"
    schedule:
      interval: "weekly"
    labels:
      - "dependencies"
      - "tooling"
      - "pre-commit"
    groups:
      pre-commit-hooks:
        patterns:
          - "*"
